### ISSUE TITLE
Please add Terrain-slope detection & splatmaps!

### ISSUE THREAD

**Issue by Thundros** [Sekuta82/ScrollingTerrain_KaiOS#1]
Hello @Sekuta82 : First off I'd like to say MARVELOUS job on this demo! It is BEAUTIFUL! Simply BEAUTIFUL! <3

Secondly, I'd like to ask if you could add 2 needed features : RGBA Splats maps with the ability to change the texture's quality for each texture splatted on the terrain with the ability to save the new terrain mesh as a gltf with the new texture quality attached? & 2nd, Terrain-slope detection?

Once again, CONGRATULATIONS on the BEAUTIFUL demo! please keep up the GREAT work! <3

**Comment by Sekuta82** [comment]
Hey @Thundros, thank you for your feedback! I'm glad you find this useful.
You could bake and add additional maps to this, like a normal map to have the normal direction available in the code.

Just for a better understanding, what do you want to do with the slope information?

**Comment by Thundros** [comment]
@Sekuta82 : I simply want to be able to specify a certain X-Angle rotation of the player, then create sliding collision / character animation slowdown to prevent the character from traveling up very steep slopes. :) And I see you are already using a shader & an RGBA splat map it looks like. Could you simply add terrain saving of new quality & texture changing quality?

Once again, thank you for all you do! :)

**Comment by Sekuta82** [comment]
Hey @Thundros, check out the latest commit. I have added a debug object that visualizes the surface normal and slope/steepness of the terrain.
The other map contains the height information and a reflection mask for the water. The blue channel is empty and can be used for something else.

**Comment by Thundros** [comment]
Please add control of the quality of the textures & an ability to save the terrain with the currently set texture.

**Comment by Sekuta82** [comment]
The textures in this sample are just placeholders for your own assets. I'm afraid you will have to create your own textures for your own projects. 
Exporting the transformed terrain mesh is a huge project of its own and outside the scope of this app. If you need to do this though, you can use most 3d tools for the task by loading in the terrain mesh and the height map and applying a displacement modifier.
